Repository fabric-community/the-hallow, pull requests merged in 2019-10, with the labels that each got.

#96 Ghastly desert + Spanish translations
  src/main/java/com/fabriccommunity/spookytime/SpookyTimeClient.java
  src/main/java/com/fabriccommunity/spookytime/block/DeaderBushBlock.java
  src/main/java/com/fabriccommunity/spookytime/block/SpookyCactusBlock.java
  src/main/java/com/fabriccommunity/spookytime/client/render/SpookyCactusEntityRenderer.java
  src/main/java/com/fabriccommunity/spookytime/entity/SpookyCactusEntity.java
  src/main/java/com/fabriccommunity/spookytime/registry/SpookyBiomes.java
  src/main/java/com/fabriccommunity/spookytime/registry/SpookyBlocks.java
  src/main/java/com/fabriccommunity/spookytime/registry/SpookyEntities.java
  src/main/java/com/fabriccommunity/spookytime/registry/SpookyFeatures.java
  src/main/java/com/fabriccommunity/spookytime/registry/SpookyWorldGen.java
  src/main/java/com/fabriccommunity/spookytime/world/SpookyBiomeSource.java
  src/main/java/com/fabriccommunity/spookytime/world/biome/GhastlyDesert.java
  src/main/java/com/fabriccommunity/spookytime/world/biome/SpookyBaseBiome.java
  src/main/java/com/fabriccommunity/spookytime/world/feature/DeaderBushFeature.java
  src/main/java/com/fabriccommunity/spookytime/world/feature/SpookyCactusFeature.java
  src/main/resources/assets/spookytime/blockstates/deader_bush.json
  src/main/resources/assets/spookytime/blockstates/spooky_cactus.json
  src/main/resources/assets/spookytime/lang/en_us.json
  src/main/resources/assets/spookytime/lang/es_es.json
  src/main/resources/assets/spookytime/models/block/deader_bush.json
  src/main/resources/assets/spookytime/models/block/spooky_cactus.json
  src/main/resources/assets/spookytime/models/item/deader_bush.json
  src/main/resources/assets/spookytime/models/item/spooky_cactus.json
  src/main/resources/assets/spookytime/textures/block/deader_bush.png
  src/main/resources/assets/spookytime/textures/block/spooky_cactus_bottom.png
  src/main/resources/assets/spookytime/textures/block/spooky_cactus_side.png
  src/main/resources/assets/spookytime/textures/block/spooky_cactus_top.png
  src/main/resources/data/spookytime/loot_tables/blocks/spooky_cactus.json
Labels: enhancement

#104 Updated fr_fr translation
  src/main/resources/assets/spookytime/lang/en_us.json
  src/main/resources/assets/spookytime/lang/fr_fr.json
  src/main/resources/fabric.mod.json
  src/main/resources/spookytime.mixins.json
Labels: translation

#108 Barrows and Spooky Forest Hills
  src/main/java/com/fabriccommunity/spookytime/registry/SpookyBiomes.java
  src/main/java/com/fabriccommunity/spookytime/registry/SpookyFeatures.java
  src/main/java/com/fabriccommunity/spookytime/registry/SpookyWorldGen.java
  src/main/java/com/fabriccommunity/spookytime/util/noise/OctaveOpenSimplexNoise.java
  src/main/java/com/fabriccommunity/spookytime/util/noise/OpenSimplexNoise.java
  src/main/java/com/fabriccommunity/spookytime/world/SpookyBiomeSource.java
  src/main/java/com/fabriccommunity/spookytime/world/SpookyChunkGenerator.java
  src/main/java/com/fabriccommunity/spookytime/world/biome/LowlandBarrowsBiome.java
  src/main/java/com/fabriccommunity/spookytime/world/biome/SpookyForestBiome.java
  src/main/java/com/fabriccommunity/spookytime/world/feature/BarrowFeature.java
  src/main/java/com/fabriccommunity/spookytime/world/feature/SpookyBiomeFeatures.java
Labels: enhancement

#94 Spooky Treasure Chests
  src/main/java/com/fabriccommunity/spookytime/SpookyTimeClient.java
  src/main/java/com/fabriccommunity/spookytime/block/SpookyTreasureChestBlock.java
  src/main/java/com/fabriccommunity/spookytime/client/SpookyClientNetworking.java
  src/main/java/com/fabriccommunity/spookytime/client/models/TreasureChestModel.java
  src/main/java/com/fabriccommunity/spookytime/client/render/SpookyTreasureChestBlockEntityRenderer.java
  src/main/java/com/fabriccommunity/spookytime/client/render/SpookyTreasureChestEntityRenderer.java
  src/main/java/com/fabriccommunity/spookytime/entity/SpookyTreasureChestBlockEntity.java
  src/main/java/com/fabriccommunity/spookytime/entity/SpookyTreasureChestEntity.java
  src/main/java/com/fabriccommunity/spookytime/mixin/client/ItemDynamicRendererMixin.java
  src/main/java/com/fabriccommunity/spookytime/registry/SpookyBlockEntities.java
  src/main/java/com/fabriccommunity/spookytime/registry/SpookyBlocks.java
  src/main/java/com/fabriccommunity/spookytime/registry/SpookyEntities.java
  src/main/resources/assets/spookytime/blockstates/spooky_treasure_chest.json
  src/main/resources/assets/spookytime/lang/en_us.json
  src/main/resources/assets/spookytime/models/block/spooky_treasure_chest.json
  src/main/resources/assets/spookytime/models/item/spooky_treasure_chest.json
  src/main/resources/assets/spookytime/textures/entity/treasure_chest/default_chest.png
  src/main/resources/data/spookytime/loot_tables/gameplay/treasure_chest_common.json
  src/main/resources/spookytime.mixins.json
Labels: enhancement

#109 Added Crows and Bread Crumbs
  src/main/java/com/fabriccommunity/spookytime/SpookyTimeClient.java
  src/main/java/com/fabriccommunity/spookytime/block/BreadCrumbsBlock.java
  src/main/java/com/fabriccommunity/spookytime/block/DeaderBushBlock.java
  src/main/java/com/fabriccommunity/spookytime/block/SpookyCactusBlock.java
  src/main/java/com/fabriccommunity/spookytime/block/SpookyTreasureChestBlock.java
  src/main/java/com/fabriccommunity/spookytime/client/SpookyClientNetworking.java
  src/main/java/com/fabriccommunity/spookytime/client/model/CrowEntityModel.java
  src/main/java/com/fabriccommunity/spookytime/client/models/TreasureChestModel.java
  src/main/java/com/fabriccommunity/spookytime/client/render/CrowEntityRenderer.java
  src/main/java/com/fabriccommunity/spookytime/client/render/SpookyCactusEntityRenderer.java
  src/main/java/com/fabriccommunity/spookytime/client/render/SpookyTreasureChestBlockEntityRenderer.java
  src/main/java/com/fabriccommunity/spookytime/client/render/SpookyTreasureChestEntityRenderer.java
  src/main/java/com/fabriccommunity/spookytime/entity/CrowEntity.java
  src/main/java/com/fabriccommunity/spookytime/entity/SpookyCactusEntity.java
  src/main/java/com/fabriccommunity/spookytime/entity/SpookyTreasureChestBlockEntity.java
  src/main/java/com/fabriccommunity/spookytime/entity/SpookyTreasureChestEntity.java
  src/main/java/com/fabriccommunity/spookytime/entity/goal/EatBreadcrumbsGoal.java
  src/main/java/com/fabriccommunity/spookytime/entity/goal/TemptBirdGoal.java
  src/main/java/com/fabriccommunity/spookytime/mixin/client/ItemDynamicRendererMixin.java
  src/main/java/com/fabriccommunity/spookytime/registry/SpookyBiomes.java
  src/main/java/com/fabriccommunity/spookytime/registry/SpookyBlockEntities.java
  src/main/java/com/fabriccommunity/spookytime/registry/SpookyBlocks.java
  src/main/java/com/fabriccommunity/spookytime/registry/SpookyEntities.java
  src/main/java/com/fabriccommunity/spookytime/registry/SpookyFeatures.java
  src/main/java/com/fabriccommunity/spookytime/registry/SpookyItems.java
  src/main/java/com/fabriccommunity/spookytime/registry/SpookySounds.java
  src/main/java/com/fabriccommunity/spookytime/registry/SpookyTags.java
  src/main/java/com/fabriccommunity/spookytime/registry/SpookyWorldGen.java
  src/main/java/com/fabriccommunity/spookytime/util/noise/OctaveOpenSimplexNoise.java
  src/main/java/com/fabriccommunity/spookytime/util/noise/OpenSimplexNoise.java
  src/main/java/com/fabriccommunity/spookytime/world/biome/GhastlyDesert.java
  src/main/java/com/fabriccommunity/spookytime/world/biome/LowlandBarrowsBiome.java
  src/main/java/com/fabriccommunity/spookytime/world/feature/BarrowFeature.java
  src/main/java/com/fabriccommunity/spookytime/world/feature/DeaderBushFeature.java
  src/main/java/com/fabriccommunity/spookytime/world/feature/SpookyBiomeFeatures.java
  src/main/java/com/fabriccommunity/spookytime/world/feature/SpookyCactusFeature.java
  src/main/resources/assets/spookytime/blockstates/bread_crumbs.json
  src/main/resources/assets/spookytime/lang/en_us.json
  src/main/resources/assets/spookytime/models/block/bread_crumbs.json
  src/main/resources/assets/spookytime/models/item/bread_crumbs.json
  src/main/resources/assets/spookytime/models/item/crow_spawn_egg.json
  src/main/resources/assets/spookytime/sounds.json
  src/main/resources/assets/spookytime/sounds/crow/crow1.ogg
  src/main/resources/assets/spookytime/sounds/crow/crow2.ogg
  src/main/resources/assets/spookytime/textures/block/bread_crumbs.png
  src/main/resources/assets/spookytime/textures/entity/crow.png
  src/main/resources/assets/spookytime/textures/item/bread_crumbs.png
  src/main/resources/data/spookytime/loot_tables/blocks/bread_crumbs.json
  src/main/resources/data/spookytime/recipes/bread_crumbs.json
Labels: enhancement

#110 Spider Lair feature
  src/main/java/com/fabriccommunity/spookytime/registry/SpookyFeatures.java
  src/main/java/com/fabriccommunity/spookytime/world/biome/HauntedUplandsBiome.java
  src/main/java/com/fabriccommunity/spookytime/world/biome/LowlandBarrowsBiome.java
  src/main/java/com/fabriccommunity/spookytime/world/biome/SpookyForestBiome.java
  src/main/java/com/fabriccommunity/spookytime/world/biome/SpookyLowlandsBiome.java
  src/main/java/com/fabriccommunity/spookytime/world/biome/SpookySwampBiome.java
  src/main/java/com/fabriccommunity/spookytime/world/feature/SpiderLairFeature.java
  src/main/java/com/fabriccommunity/spookytime/world/feature/SpookyBiomeFeatures.java
  src/main/resources/assets/spookytime/lang/fr_fr.json
  src/main/resources/data/spookytime/loot_tables/chests/spider_lair.json
Labels: enhancement

#125 Spanish translation updates
  src/main/resources/assets/spookytime/lang/es_es.json
  src/main/resources/fabric.mod.json
Labels: enhancement

#111 Witches Melt In Water
  src/main/java/com/fabriccommunity/spookytime/SpookyTime.java
  src/main/java/com/fabriccommunity/spookytime/block/BleedingBlock.java
  src/main/java/com/fabriccommunity/spookytime/block/TaintedSandBlock.java
  src/main/java/com/fabriccommunity/spookytime/block/WitchWaterBubbleColumnBlock.java
  src/main/java/com/fabriccommunity/spookytime/event/WitchTickCallback.java
  src/main/java/com/fabriccommunity/spookytime/mixin/ThrownPotionEntityMixin.java
  src/main/java/com/fabriccommunity/spookytime/mixin/WitchEntityMixin.java
  src/main/java/com/fabriccommunity/spookytime/registry/SpookyEvents.java
  src/main/resources/assets/spookytime/blockstates/bleeding_block.json
  src/main/resources/assets/spookytime/lang/en_us.json
  src/main/resources/assets/spookytime/models/block/bleeding_block.json
  src/main/resources/assets/spookytime/models/item/bleeding_block.json
  src/main/resources/assets/spookytime/textures/block/bleeding_block.png
  src/main/resources/assets/spookytime/textures/block/bleeding_block.png.mcmeta
  src/main/resources/spookytime.mixins.json
Labels: enhancement

#140 Add Paper Bag item, round 2
  src/main/java/com/fabriccommunity/spookytime/item/PaperBagItem.java
  src/main/java/com/fabriccommunity/spookytime/mixin/EndermanEntityMixin.java
  src/main/java/com/fabriccommunity/spookytime/registry/SpookyItems.java
  src/main/resources/assets/spookytime/lang/en_us.json
  src/main/resources/assets/spookytime/models/item/paper_bag.json
  src/main/resources/assets/spookytime/textures/item/paper_bag.png
  src/main/resources/data/spookytime/recipes/paper_bag.json
  src/main/resources/spookytime.mixins.json
Labels: enhancement

#150 Stone circle tweaks and loot chest 1/3 of time therein
  src/main/java/com/fabriccommunity/spookytime/world/feature/BarrowFeature.java
  src/main/java/com/fabriccommunity/spookytime/world/feature/SpookyBiomeFeatures.java
  src/main/java/com/fabriccommunity/spookytime/world/feature/StoneCircleFeature.java
  src/main/resources/data/spookytime/loot_tables/chests/stone_circle.json
Labels: enhancement, world gen

#148 #138 Add decorative Tombstone
  src/main/java/com/fabriccommunity/spookytime/block/TombstoneBlock.java
  src/main/java/com/fabriccommunity/spookytime/registry/SpookyBlocks.java
  src/main/resources/assets/spookytime/blockstates/tombstone.json
  src/main/resources/assets/spookytime/models/block/tombstone.json
  src/main/resources/assets/spookytime/models/item/tombstone.json
  src/main/resources/assets/spookytime/textures/block/tombstone.png
  src/main/resources/assets/spookytime/textures/item/tombstone.png
  src/main/resources/data/spookytime/loot_tables/blocks/tombstone.json
  src/main/resources/data/spookytime/recipes/tombstone.json
Labels: enhancement, good first issue

#105 Blood Crafting Recipe Type
  src/main/java/com/fabriccommunity/spookytime/SpookyTime.java
  src/main/java/com/fabriccommunity/spookytime/block/BloodBlock.java
  src/main/java/com/fabriccommunity/spookytime/block/CraftingFluidBlock.java
  src/main/java/com/fabriccommunity/spookytime/block/WitchWaterBlock.java
  src/main/java/com/fabriccommunity/spookytime/exception/InvalidJsonException.java
  src/main/java/com/fabriccommunity/spookytime/recipe/blood/BloodRecipe.java
  src/main/java/com/fabriccommunity/spookytime/recipe/blood/BloodRecipeSerializer.java
  src/main/java/com/fabriccommunity/spookytime/recipe/witchwater/WitchWaterRecipe.java
  src/main/java/com/fabriccommunity/spookytime/recipe/witchwater/WitchWaterRecipeSerializer.java
  src/main/java/com/fabriccommunity/spookytime/registry/SpookyRecipes.java
  src/main/resources/data/spookytime/recipes/purple_wool.json
  src/main/resources/data/spookytime/recipes/red_wool.json
Labels: enhancement, fix conflicts
